### ISSUE TITLE
How to get this info?

### ISSUE THREAD

**Issue by dzulhelmi** [Livefyre/streamhub-wall#111]
"network": "livefyre.com",
            "siteId": "313878",
            "articleId": "1",
            "environment": "livefyre.com"

What are those siteID? articleId? network?
If i am going to pull social media stream from a certain celebrity social media acccount, what should i fill for those field above?

**Comment by gobengo** [comment]
Social Media aggregation into Livefyre Collections requires purchasing a Livefyre Subscription. Do you or your employer have one? http://web.livefyre.com/engagement-cloud/

**Comment by dzulhelmi** [comment]
How to subscribe?

**Comment by gobengo** [comment]
Fill out the form on http://livefyre.com/learnmore
