### ISSUE TITLE
"initial" option causes strange behavior 

### ISSUE THREAD

**Issue by hctom** [Livefyre/streamhub-wall#64]
I noticed some strange behavior when using the initialization like so:

```
Livefyre.require(['streamhub-wall#3'],
function (LiveMediaWall) {
    var wall = window.wall = new LiveMediaWall({
        el: document.getElementById("wall"),
        initial: 10,
        minContentWidth: 300,
        collection: {
          "network": "livefyre.com",
          "siteId": "313878",
          "articleId": "1",
          "environment": "livefyre.com"
        },
        postButton: true
    });
});
```

In my case there are no 10 items visible on initialization and when resizing the browser window, there are even less items visible initially while also resulting in strange click behaviors on the "Load more" button (needs to be clicked several times until there are new items loaded).

To reproduce, just add a ```LiveMediaWall``` to a page and resize the browser width back and forth and see what's happening. Also, load the page, click "Load more" several times and then start browser width resizing. This results in "lost" items which are not visible anymore and do not reappear when clicking "Load more".

Without the ```initial``` option set, everything seems to work fine.

**Comment by gobengo** [comment]
I believe this is fixed in latest. Sorry for the late reply

Example: http://jsbin.com/mafoboboda/1/edit
