### ISSUE TITLE
Twitter and Facebook share buttons have no action on mobile

### ISSUE THREAD

**Issue by jsoningram** [Livefyre/streamhub-wall#81]
I'm using the code provided by the Livefyre studio to create a media wall. On desktop, clicking the share button shows the choice of Facebook, Twitter or a link. Clicking either the Facebook or Twitter links produces a pop up window allowing you to share the post. 

On mobile, I get the choice of either FB or Twitter, but the links have no action. No pop up window allowing me to share.

Tested on iPhone 6, Safari. Latest update as of 10-28-15.

![screen shot 2015-10-26 at 3 21 07 am](https://cloud.githubusercontent.com/assets/1622480/10726652/4aa64f30-7b91-11e5-9420-bafa774356c2.png)

**Comment by ross-pfahler** [comment]
Hi @jsoningram,

Thanks for the bug report. We released a fix for this on November 19th -- you can find the release notes at: http://answers.livefyre.com/developers/reference/release-notes/11-19-2015/

Thank you!
